version: '3'

services:

  apache:
    build: ./.docker/apache
    volumes:
      - ./:/var/www/html
    ports:
     - ${HTTP_PORT}:80
     - ${HTTPS_PORT}:443

  nginx:
    build: ./.docker/nginx
    volumes:
      - ./:/var/www/html
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    depends_on:
      - phpfpm

  phpfpm:
    build: ./.docker/phpfpm
    volumes:
      - ./:/var/www/html